# Reference architectures # {#reference-architectures}

In this section,
we discuss the [business and organisational architecture](#business-organisational-architecture),
including how it aligns with the business and organisational building blocks.
Next, we discuss the [technical architecture](#technical-architecture),
including how it aligns with the technical building blocks, and
the standards and protocols that we recommend.

<pre class=include>
path: business-organisational-architecture.bs
</pre>

<pre class=include>
path: technical-architecture.bs
</pre>
