<pre class='metadata'>
Title: LDT Interoperability Blueprint
Shortname: ldt-interoperability-blueprint
Warning: Not Ready
Level: none
Status: LD
Editor: Pieter Heyvaert, Ghent University - imec http://idlab.ugent.be/, pieter.heyvaert@ugent.be
Editor: Sille Sepp, TalTech https://taltech.ee/
Editor: Laura Riou, Cerema https://www.cerema.fr
Editor: Lucas Vieira Magalhães, LIST https://www.list.lu/
Editor: Thimo Thoeye, OASC https://oascities.org/
Abstract: To-do
Markup Shorthands: markdown yes, css no
Canonical URL: _ORCHESTRATOR_CURRENT_BUILD_FULL_LINK_
ED: _ORCHESTRATOR_CURRENT_BUILD_FULL_LINK_
Previous Version: _ORCHESTRATOR_PREVIOUS_BUILD_FULL_LINK_
Repository: https://github.com/ldt4ssc/interoperability-blueprint
Boilerplate: copyright no, conformance no, references no
Local Boilerplate: logo yes
Dark Mode: no
</pre>

<link rel="stylesheet" href="css/style.css">

# Introduction # {#introduction}

The Interoperability Blueprint provides business, organisational, and technical guidelines for
building our own Local Digital Twin (LDT) and interconnecting with other LDTs.
An LDT is a digital representation of physical assets, systems, or processes in a defined local context
(for example, city, district, building, industry, port, and airport).
LDTs are based on structured data models and contextualised data.
They leverage either historical data, near real-time data, or real-time data, and
they enable visualisation, analysis, simulation, and reasoning services
that support decision-making.
First, we will elaborate on [why LDTs can be useful](#why-use-an-ldt),
followed by a [high-level overview of an LDT](#high-level-overview-ldt).
Next, we will explain the importance of being able to add new components to an LDT (Section 1.3) and
discover existing components that can be added to an LDT (Section 1.4).
Finally, we will discuss how this blueprint aligns with Minimum Interoperability Mechanisms (MIMs) Plus (Section 1.5)
and how data spaces and LDTs are related (Section 1.6).
The remainder of this deliverable is structured as follows:

- Chapter 2: The business and organisational building blocks and the technical building blocks.
- Chapter 3: The workflows an LDT should support.
- Chapter 4: The technical architecture and the business and organisational overview.
- Chapter 5: How the business and organisational architecture and technical architecture support the workflows.
- Chapter 6: How to build an LDT based on the other chapters.

Although this blueprint mainly guides us through the process of building a new LDT with the focus on interoperability,
we can also use its recommendations for updating an existing LDT and interlinking LDTs.
The scope of the blueprint isn’t to offer guidelines for every use case in
which an LDT is being built or has been built, as every LDT operates in a very specific context.

## Why use an LDT ## {#why-use-an-ldt}

An LDT is a virtual replica of a territory based on structured data models, real-time data
feeds, and potentially 3D representations,
which can integrate simulation models (flows, usage, impacts, and so on).
It aims to dynamically represent the territory at various spatial
and temporal scales to analyse, understand, anticipate, and simulate the effects of public
policies, environmental hazards, climate change, development projects or disruptions.
The digital twin supports strategic decision-making, consultation, foresight, and scenario design.
It can even include automated decision-making and execution.
It can incorporate historical datasets, time-delayed data, Building Information Modelling (BIM),
Geographic Information Systems (GIS), and/or specific models (mobility, climate, energy, and so on).
LDTs can offer
the [following capabilities](https://www.etsi.org/deliver/etsi_gr/CIM/001_099/017/01.01.01_60/gr_CIM017v010101p.pdf)
to users:

- Descriptive: Current (and past) state of the real-world asset - static and dynamic.
    Bidirectional connection between real-world assets and the LDT.
- Predictive: Extends the descriptive capability by providing predictions on the way the real asset could evolve
    in the future, using predictive models to envision possible futures.
- Prospective: Conducts "what-if" analyses to evaluate the potential consequences of actions.
- Prescriptive: Extends (or, in extreme cases, executes) the prospective capability with suggested actions on
    the real system to achieve a given objective based on the analysis.
- Diagnostic: Explains situations or alerts about deviations from expected conditions.
    Capability for evaluating what happened, especially in the case of a malfunction of the real asset.

Note that we do not derive this definition of an LDT from a formal international standard.
Instead, it is a project-specific conceptualisation influenced by existing frameworks such as
Digital Twins, the EU LDT Toolbox, MIMs Plus 8 on Local Digital Twins, Smart City models,
and Data Spaces. While relevant standards (for example, ISO 23247, ISO/IEC 30182, and
ISO 30173) provide partial guidance, there is currently no universally accepted standard
definition for LDTs in the context of urban or territorial systems.

## High-level overview of an LDT ## {#high-level-overview-ldt}

<figure id="fig-high-level-ldt">
<img id="high-level-ldt" alt="TO-DO" src="img/high-level-ldt.jpg">
<figcaption>Test</figcaption>
</figure>

## Adding a new Surface-level component to an existing LDT ## {#adding-new-slc-to-existing-ldt}

<figure>
<img id="ldt-add-new-slc" alt="TO-DO" src="img/ldt-add-new-slc.jpg">
<figcaption>Test</figcaption>
</figure>

## Discovering which Surface-level components work on which existing LDTs ## {#discover-slc-existing-ldt}

<figure>
<img id="ldt-discovery" alt="TO-DO" src="img/ldt-discovery.jpg">
<figcaption>Test</figcaption>
</figure>

## Alignment with MIMs Plus ## {#alignment-mims}

<figure>
<img id="ldt-mim8" alt="TO-DO" src="img/ldt-mim8.jpg">
<figcaption>Test</figcaption>
</figure>

## Relationship between data spaces and LDTs ## {#relationship-data-spaces}

# LDT building blocks based on DSSC & DS4SSCC-DEP building blocks # {#building-blocks}

## Business and organisational building blocks ## {#business-organisational-building-blocks}

<figure>
<img id="img-business-organisational-building-blocks" alt="TO-DO" src="img/business-organisational-building-blocks.jpg">
<figcaption>Test</figcaption>
</figure>

## Technical building blocks ## {#technical-building-blocks}

<figure>
<img id="img-technical-building-blocks" alt="TO-DO" src="img/technical-building-blocks.jpg">
<figcaption>Test</figcaption>
</figure>

# Workflows # {#workflows}

## Adding a new Surface-level component to an existing LDT ## {#workflow-adding-new-slc-existing-ldt}

## Discovering which Surface-level components work on an existing LDT ## {#workflow-discover-slc-existing-ldt}

# Reference architectures # {#reference-architectures}

## Business and organisational architecture ## {#business-organisational-architecture}

## Technical architecture ## {#technical-architecture}

<figure>
<img alt="TO-DO" src="img/architecture-everything.jpg">
<figcaption>Test</figcaption>
</figure>

### Support different data models ### {#support-different-data-models}

<figure>
<img id="focus-on-data-models" alt="TO-DO" src="img/focus-on-data-models.jpg">
<figcaption>Test</figcaption>
</figure>

### Support different data exchange types ### {#support-different-data-exchange-types}

<figure>
<img id="focus-on-data-exchange-types" alt="TO-DO" src="img/focus-on-data-exchange-types.jpg">
<figcaption>Test</figcaption>
</figure>

### Support for the usage of data from different LDTs ### {#support-different-data}

<figure>
<img id="focus-on-sharing-data-between-ldts" alt="TO-DO" src="img/focus-on-sharing-data-between-ldts.jpg">
<figcaption>Test</figcaption>
</figure>

### Support for working with different AI models ### {#support-different-ai-models}

<figure>
<img id="how-ai-components-work" alt="TO-DO" src="img/how-ai-components-work.jpg">
<figcaption>Test</figcaption>
</figure>

### Standards and protocols ### {#standards-protocols}

#### Artefacts #### {#artefacts}

#### Interaction between components #### {#interaction-components}

# Workflows using reference architectures # {#workflows-architectures}

## Adding a new Surface-level component to an existing LDT ## {#workflow-architecture-adding-new-slc-existing-ldt}

## Discovering which Surface-level components work on an existing LDT ## {#workflow-architecture-discover-slc-existing-ldt}

# How to build an LDT # {#how-to-build-ldt}

## Explore and validate ## {#explore-validate}

## Define and implement ## {#define-implement}

### How to build a Data Acquisition component ### {#how-to-build-data-acquisition}

### How to build a Data Management component ### {#how-to-build-data-management}

### How to build a Connectivity component ### {#how-to-build-connectivity}

### How to build Decision-Making components ### {#how-to-build-decision-making}

### How to build Analysis components ### {#how-to-build-analysis}

### How to build Visualisations ### {#how-to-build-visualisations}
