# LDT building blocks based on DSSC & DS4SSCC-DEP building blocks # {#building-blocks}

Building on the fact that LDTs can act as data consumers and data providers in data space ecosystems
([[#relationship-data-spaces]]),
this blueprint proposes to reuse the DSSC & DS4SSCC-DEP Blueprints and their building blocks
to a certain extent (see [Figure 7](#fig-blueprints)).
The [DSSC Blueprint](https://blueprint.dssc.eu/) defines a set of business, organisational, and technical building blocks,
which need to be implemented in the context of data spaces.
The application of each of these building blocks in the context of smart cities and communities was refined
in the
[DS4SSCC-DEP project](https://static1.squarespace.com/static/63718ba2d90d0263d7fc1857/t/696e156b592f0c60d9d9f764/1768822123196/2.+Blueprint+Evolution.pdf).
Here, relevant implementations for each building block were identified.
In LDT4SSC, these refined and detailed building blocks are then applied to
the context of interconnected local digital twins.
Again, practical implementations are identified, and new, LDT-specific building blocks are added.

<figure id="fig-blueprints">
  <img id="blueprints" alt="TO-DO" src="img/blueprints.jpg">
  <figcaption>
    The DSSC Blueprint was used by the DS4SSCC-DEP Blueprint.
    The LDT4SSC Blueprint uses the DS4SSCC-DEP Blueprint and, consequently, the DSSC Blueprint.
  </figcaption>
</figure>

In [[#business-organisational-building-blocks]] and [[#technical-building-blocks]],
we list the business and organisational building blocks and the
technical building blocks, respectively.
The blocks' summaries are altered to fit LDTs, instead of data spaces.
For their full descriptions,
we refer to the [DSSC Blueprint v3 (released in March 2026)](https://blueprint.dssc.eu/) and
[DS4SSCC-DEP Blueprint (published in Sept 2025)](https://static1.squarespace.com/static/63718ba2d90d0263d7fc1857/t/696e156b592f0c60d9d9f764/1768822123196/2.+Blueprint+Evolution.pdf).
In the case of a new business and organisational building block,
we add a more detailed description referring to available academic and grey literature.
In case of a new technical building block,
we refer to [[#technical-architecture]] and [[#define-implement]].
If the LDT is part of a data space,
we need to take into account the building blocks on both the levels of the LDT and the data space.

## Business and organisational building blocks ## {#business-organisational-building-blocks}

An essential part of LDTs' interoperability is the business and organisational aspects that
define the purpose, organisational context (including involved stakeholders and their roles),
incentives, rules and processes for designing, deploying, and operating LDTs.
This section explains which business and organisational building blocks are important for either building
LDTs or interconnecting LDTs.
[Figure 8](#fig-img-business-organisational-building-blocks) provides a visual overview of these building blocks in
four pillars: business, governance, legal and design.

<figure id="fig-img-business-organisational-building-blocks">
  <img id="img-business-organisational-building-blocks" alt="TO-DO" src="img/business-organisational-building-blocks.jpg">
  <figcaption>
    Business and organisational building blocks,
    based on theDSSC/DS4SSCC-DEP building blocks and evolved as part of the LDT4SSC project.
  </figcaption>
</figure>

The **Business pillar** of LDTs frames the context for value creation, value capture and
feasibility for sustaining the LDT beyond initial testing and piloting.
This pillar of building blocks explores how to identify
stakeholder incentives and structure data and service offerings.
At its core, the business model should address the motives and strategic objectives of relevant stakeholders,
ensure their alignment with offered data and services,
foster multi-stakeholder data cooperations, and be sustainable in the long-run.
This pillar includes the following blocks:

- [**Business Model**](https://blueprint.dssc.eu/?pane=business&business=business-model):
    This building block provides insight into establishing the value creation and value capture mechanisms,
    alongside other related business model elements
    (such as cost structures, revenue streams, funding models, public-private collaboration challenges...),
    for both the LDT Base and Core (for example, if based on a data space), and the central use case(s) the LDT enables.
- [**Use Case Development**](https://blueprint.dssc.eu/?pane=business&business=use-case-development):
    This building block shows how to identify, refine, implement and improve a use case.
- **LDT Services as Data Space Offerings**:
    Whereas in data spaces, both data, data products and services are considered as data space offerings,
    in the context of LDTs, this building block emphasises the offering of LDT services from
    a business perspective and provides a strategy to develop and maintain them.
    More details in the
    [DSSC blueprint v3, section Data Space Offerings](https://blueprint.dssc.eu/?pane=business&business=data-space-offerings).
- [**Intermediaries and Operators**](https://blueprint.dssc.eu/?pane=business&business=intermediaries-and-operators):
    Intermediaries and operators may have a significant role in fostering data exchange among
    (data space) participants, providing essential functionalities, as well as value-added services.
    In multi-actor environments, intermediaries may also foster interoperability,
    with diverse technical and non-technical implementations.

In addition, the **Governance pillar** ensures that the operating model of a single LDT or
its interconnection with other LDTs is aligned with its core purpose.
It sets clear roles and responsibilities, rules, and processes, among others,
to ensure trust among engaged stakeholders and beneficiaries, foster clear and transparent decision-making, and
support operational compliance with relevant regulations and requirements.
This pillar includes the following building blocks:

- [**Organisational Form and Governance Authority**](https://blueprint.dssc.eu/?pane=business&business=organisational-form-and-governance-authority):
    In case the LDT Base and Core are built on multi-stakeholder data cooperations, clarifying its organisational form
    (either as incorporated or unincorporated) may be useful.
    This building block provides guidance on the various types of entities stakeholders may establish,
    emphasises the governance authority (for example, setting the rules of the chosen data cooperation,
    defining the governance framework, ensuring compliance, and resolving conflicts,
    thereby fostering trust and data quality).
- [**Participation Management**](https://blueprint.dssc.eu/?pane=business&business=participation-management):
    In case the LDT Base and Core require the participation of multiple actors,
    this building block helps to clarify how to identify potential participants and manage
    their onboarding and offboarding, emphasising the risks associated with poorly managed participation,
    including data governance challenges and reduced collaboration.
    The building block highlights the need for clear rules, inclusive governance, and regulatory compliance.

In addition to having clear and strong governance,
the **Legal pillar** emphasises the necessity for ensuring regulatory compliance and
a strong legal foundation for the LDT's operations.
It defines the following blocks:

- [**Regulatory Compliance**](https://blueprint.dssc.eu/?pane=business&business=regulatory-compliance):
    An LDT is subject to both data and digital, sector-specific or other regulations, and as such,
    this building block indicates how to ensure regulatory compliance of the envisioned data cooperations,
    the use and sharing of data, and the provision of LDT services.
    It outlines actions to be undertaken by participants or potential policies that the governance authority shall consider.
    The building block is focusing on legal triggers, in other words, elements, criteria or events that have occurred
    in a particular context and signal that a specific legal framework must or should be applied.
- [**Contractual Framework**](https://blueprint.dssc.eu/?pane=business&business=contractual-framework):
    While the governance framework sets out the principles, processes, standards, protocols, rules and practices that
    guide and regulate the governance, management and operations, those agreements also need a legal basis.
    This building block provides an overview of the types of legal agreements
    that are essential for data cooperations, categorising agreements according to their objectives,
    for example, institutional agreements, data sharing agreements, and service agreements.
    For each category of agreements, it highlights horizontal issues that are likely to emerge or take into account
    common regulations across all sectors
    (for example, the requirement of fairness in data contracts).

Finally, the LDT4SSC Blueprint defines a **Design pillar** with two essential building blocks
which will influence how the LDTs are built, sustained and adopted,
influencing all other business and organisational as well as technical building blocks,
enabling the alignment of technological innovation with societal and environmental goals,
fostering trust and long-term value for all users and citizens.

- **User Experience (UX)**:
    Whereas user interfaces for various LDT services, such as
    visualisation, analytics, simulations and so on, have a technical perspective,
    these also hold non-technical design choices to ensure usability, accessibility, and trust
    while maintaining system performance, monitored through clearly defined KPIs
    such as user adoption rates, task completion efficiency, and decision impact.
    As such, this building block emphasises the importance of a user-centric design of LDTs,
    including their monitoring, to align interface design with user needs, decision-making contexts,
    and cognitive capacities.
    Firstly, interfaces should provide clear and intuitive navigation, flexible data-layer management, and
    immediate visual feedback, supported by onboarding tools and training materials.
    Secondly, effective interfaces integrate spatial visualisation (3D models, overlays, linked charts, VR/XR) with
    analytical clarity and role-based customisation, enabling various types of users
    (planners, policymakers, citizens, and others) to explore both real-time and historical data through
    synchronised views and scenario-based simulations.
    Thirdly, users' visual and cognitive diversity should be considered and catered to,
    supporting accessibility (for example, [WCAG compliance](https://www.w3.org/WAI/standards-guidelines/wcag/)).
    In addition, transparency of data sources and data processing,
    including alignment with privacy-by-design principles (such as Gemini Principles), are essential to build
    user trust and inclusivity. Fourthly, co-design approaches such as actively involving
    stakeholders in early design and iterative testing ensure relevance, usability, and
    shared understanding of LDT concepts, as highlighted in studies
    such as
    BEAM ([Ignatius et al., 2025](https://iopscience.iop.org/article/10.1088/1742-6596/3140/20/082017)) and
    [FLOODTWIN (Frontiers, 2025)](https://www.frontiersin.org/journals/environmental-science/articles/10.3389/fenvs.2025.1724250/full).
    Finally, continuous UX evaluation should combine standardised questionnaires
    (for example, [UEQ](https://web.archive.org/web/20171001122308/http://www.ueq-online.org/),
    [SUS](https://en.wikipedia.org/wiki/System_usability_scale)),
    task-based usability testing, cognitive load measures
    (for example, [NASA-TLX](https://www.nasa.gov/human-systems-integration-division/nasa-task-load-index-tlx/)), and
    usage analytics to monitor effectiveness and identify friction points.
- **Responsible Digital Practices**:
    This building block refers to design principles that
    encourage environmentally sustainable digitalisation efforts, while building and deploying LDTs.
    Taking into consideration [the increasing and transformative impact
    the digital sector has on the environment and society](https://arxiv.org/abs/2102.02622),
    this building block is designed to embed environmental sustainability, ethics, and social responsibility into
    the core of LDTs and its digital infrastructure.
    It aims to minimise the environmental footprint of digital technologies through measuring its impact
    ([life cycle assessment](https://www.itu.int/myworkspace/t-rec/item?id=16010&lang=en),
    [software-assisted](https://landscape.bundesverband-green-software.de/)),
    [eco-design](https://www.arcep.fr/uploads/tx_gspublication/general_policy_framework_for_the_ecodesign_of_digital_services_version_2024.pdf),
    energy efficiency, and circular economy practices
    throughout the lifecycle phases of the LDT, from design and development to
    decommissioning and end-of-life, including operations and maintenance.

The aforementioned building blocks are implemented in various ways, using specific assets,
inter alia contracts and rulebooks, or specific methodologies and templates,
inter alia the
[LDT4SSC Methodology](https://knowledgehub.ldt4ssc.eu/resources_content/non_tech_resources/#the-ldt4ssc-methodology),
[Data Cooperation Canvas](https://www.datacooperationcanvas.eu/canvas/intro), and/or various ecosystem design materials.

The business and organisational building blocks are further described in the Business and
Organisational Architecture in [[#business-organisational-architecture]],
emphasising their connections and relevance for LDTs interoperability.

## Technical building blocks ## {#technical-building-blocks}

This section explains what technical pillars and building blocks are required to build an LDT.
[Figure 9](#fig-img-technical-building-blocks) contains a graphical overview of these pillars and blocks,
which we will discuss in detail next.

<figure id="fig-img-technical-building-blocks">
  <img id="img-technical-building-blocks" alt="TO-DO" src="img/technical-building-blocks.jpg">
  <figcaption>
    Technical LDT building blocks aligned with the LDT levels,
    based on the DSSC/DS4SSCC-DEP building blocks.
  </figcaption>
</figure>

The **Data Interoperability pillar** contains the capabilities needed for data acquisition,
data exchange, semantic models, data formats, and application interfaces.
This also includes functionalities for provenance and traceability.
This pillar has the following building blocks,
which apply to interactions within a single LDT and between LDTs:

- [**Data Models**](https://blueprint.dssc.eu/?pane=technical&technical=data-models) (Core and Surface):
    Capabilities to define and use shared semantics.
- [**Data Exchange**](https://blueprint.dssc.eu/?pane=technical&technical=data-exchange) (Core and Surface):
    Capabilities relating to the actual exchange and sharing of data.
- [**Provenance, Traceability & Observability**](https://blueprint.dssc.eu/?pane=technical&technical=provenance-traceability-observability)
    (Core and Surface):
    Capabilities for tracking the data sharing process so
    it becomes traceable and can be checked for compliance purposes.
- **Data Acquisition** (Base and Core):
    Capabilities to extract, transform, and load data from multiple data sources, while assuring data quality.
    This is a new LDT-specific  building block,
    because the Data Model block only considers the semantics of then data, and the Data Exchange block only considers
    the exchange and sharing of data after the LDT has acquired it.
    The concrete capabilities are
    - Data extraction: Extra data from multiple data sources that might use different formats and data models.
    - Data transformation: Transform data to different data formats and data models.
    - Data loading: Load and store the data so that other components of the LDT can use it.

The **Data Sovereignty and Trust pillar** contains the capabilities needed for
identifying components and assets that interact within an LDT and between LDTs.
This allows establishing trust and the possibility of defining and enforcing policies for access and usage control.
This pillar has the following building blocks:

- [**Identity and Attestation Management**](https://blueprint.dssc.eu/?pane=technical&technical=identity-attestation-management)
    (Core and Surface):
    Capabilities to manage identities and attestations of components to ensure
    the reliability and integrity of components' information.
- [**Trust Framework**](https://blueprint.dssc.eu/?pane=technical&technical=trust-framework) (Core and Surface):
    Capabilities to verify that a component adheres to certain rules.
- [**Access and Usage Policies Enforcement**](https://blueprint.dssc.eu/?pane=technical&technical=access-usage-policies-enforcement)
    (Core):
    Capabilities to specify and enforce access and usage policies.

The **Data Value Creation Enablers pillar** contains the capabilities for enabling value creation on top of LDTs:
providing metadata on data products and publishing them in catalogues.
This pillar has the following building blocks:

- [**Data, Services and Offering Descriptions**](https://blueprint.dssc.eu/?pane=technical&technical=data-services-and-offerings-descriptions)
    (Core and Surface):
    Capabilities to describe data, services and offerings in a manner that will be understandable by
    any component that interacts with(in) LDTs.
- [**Publication and Discovery**](https://blueprint.dssc.eu/?pane=technical&technical=publication-and-discovery)
    (Core and Surface):
    Capabilities to publish the description of data, services and offerings so that
    they can be discovered by potential data users.

The **Service Creation Enablers pillar** contains the capabilities for enabling service creation on top of LDTs:
ensuring accessibility and inclusive user experience (UX)/user interface (UI),
developing and deploying AI models, and running simulations.
This is a new LDT-specific pillar, because creating service is as important as the data itself.
It's based on the
[Value Creation Services building block of data spaces](https://blueprint.dssc.eu/?pane=technical&technical=value-creation-services),
which we don't include in the Data Value Creation Enablers pillar for an LDT.
The new Service Creation Enablers pillar has the following building blocks:

- **Visualisation** (Surface):
    Capability to develop visualisations of the data while ensuring their accessibility and the inclusiveness of the UI.
- **Analysis** (Surface):
    Capabilities to develop and deploy AI models, and to enable the exploration of dynamic behaviours and scenarios within LDTs.
    This supports testing of policies, systems, or interventions under different assumptions.
    This is a new LDT-specific building block due to the importance of AI and the consequences of its usage, and
    the importance of running simulations on an LDT's data. The concrete capabilities are
    - AI model development: Develop and manage AI models on top of the LDT's data.
    - AI model deployment: Deploy AI models, either developed by the LDT or by external parties,
        on top of the LDT's data.
- **Decision-Making** (Surface):
    Capability to support decision-making, such as planning,
    participation channels, and notifications.
    This is a new LDT-specific building block due to the importance of supporting decision-making when
    creating a service on top of an LDT.
