# How to build an LDT # {#how-to-build-ldt}

In this chapter,
we discuss how we can build an LDT based on the [reference architectures](#reference-architectures),
following
the [LDT4SSC Methodology](https://knowledgehub.ldt4ssc.eu/resources_content/non_tech_resources/#the-ldt4ssc-methodology)
(see [Figure 19](#fig-how-to-build-an-ldt).
First, we discuss [how to explore and validate an LDT as a solution](#explore-validate).
Next, we discuss [how to define and implement an LDT](#define-implement).
Note that participatory, user-centred, and service design methods are used throughout the 4 steps.

<figure id="fig-how-to-build-an-ldt">
  <img id="img-how-to-build-an-ldt" alt="TO-DO" src="img/how-to-build-an-ldt.jpg">
	<figcaption>
		The LDT4SSC methodology for building an LDT consists of 4 steps
    (EXPLORE, VALIDATE, DEFINE, and IMPLEMENT).
	</figcaption>
</figure>

<pre class=include>
path: explore-validate.bs
</pre>

<pre class=include>
path: define-implement.bs
</pre>
