<pre class='metadata'>
Title: LDT Interoperability Blueprint
Shortname: ldt-interoperability-blueprint
Level: none
Status: LD
Editor: Pieter Heyvaert, Ghent University - imec http://idlab.ugent.be/, pieter.heyvaert@ugent.be
Editor: Sille Sepp, TalTech https://taltech.ee/
Editor: Laura Riou, Cerema https://www.cerema.fr
Editor: Lucas Vieira Magalhães, LIST https://www.list.lu/
Editor: Juan Francisco Inglés, Libelium https://www.libelium.com/
Editor: Thimo Thoeye, OASC https://oascities.org/
Abstract: The Interoperability Blueprint provides guidelines on how to build a Local Digital Twin (LDT).
  The blueprint has a focus on an LDT's interoperability to enable
  - the easy addition of new Surface-level components on top of existing LDTs, including visualisations, analysis, and decision-making,
  - the reuse of Core and Base-level components for the development of new services,
  - the easy discovery of which Surface-level components work on which existing LDTs,
  - the interconnection of different LDTs to allow the cost-effective exchange of LDT components.

  To achieve this, the blueprint includes
  - LDT building blocks, based on the existing building blocks for data spaces,
  - workflows that describe how these interoperability features work in practice,
  - reference architectures that support these features,
  - explanations of how the architectures support the workflows, and
  - guidelines on how to build an LDT using the LDT4SSC Methodology.
Markup Shorthands: markdown yes, css no
Canonical URL: _ORCHESTRATOR_CURRENT_BUILD_FULL_LINK_
ED: _ORCHESTRATOR_CURRENT_BUILD_FULL_LINK_
Previous Version: _ORCHESTRATOR_PREVIOUS_BUILD_FULL_LINK_
Repository: https://github.com/ldt4ssc/interoperability-blueprint
Boilerplate: copyright no, conformance no, references no
Local Boilerplate: logo yes
Dark Mode: no
</pre>

<link rel="stylesheet" href="css/style.css">

<pre class=include>
path: introduction.bs
</pre>

<pre class=include>
path: building-blocks.bs
</pre>

<pre class=include>
path: workflows.bs
</pre>

<pre class=include>
path: reference-architectures.bs
</pre>

<pre class=include>
path: workflows-using-reference-architectures.bs
</pre>

<pre class=include>
path: how-to-build-ldt.bs
</pre>

<script src="js/main.js"></script>
