<pre class='metadata'>
Title: LDT Interoperability Blueprint
Shortname: ldt-interoperability-blueprint
Warning: Not Ready
Level: none
Status: LD
Editor: Pieter Heyvaert, Ghent University - imec http://idlab.ugent.be/, pieter.heyvaert@ugent.be
Editor: Sille Sepp, TalTech https://taltech.ee/
Editor: Laura Riou, Cerema https://www.cerema.fr
Editor: Lucas Vieira Magalhães, LIST https://www.list.lu/
Editor: Juan Francisco Inglés, Libelium https://www.libelium.com/
Editor: Thimo Thoeye, OASC https://oascities.org/
Abstract: To-do
Markup Shorthands: markdown yes, css no
Canonical URL: _ORCHESTRATOR_CURRENT_BUILD_FULL_LINK_
ED: _ORCHESTRATOR_CURRENT_BUILD_FULL_LINK_
Previous Version: _ORCHESTRATOR_PREVIOUS_BUILD_FULL_LINK_
Repository: https://github.com/ldt4ssc/interoperability-blueprint
Boilerplate: copyright no, conformance no, references no
Local Boilerplate: logo yes
Dark Mode: no
</pre>

<link rel="stylesheet" href="css/style.css">

<pre class=include>
path: introduction.bs
</pre>

<pre class=include>
path: building-blocks.bs
</pre>

<pre class=include>
path: workflows.bs
</pre>

<pre class=include>
path: reference-architectures.bs
</pre>

<pre class=include>
path: workflows-using-reference-architectures.bs
</pre>

<pre class=include>
path: how-to-build-ldt.bs
</pre>
